# Used solely for docker-compose build
version: '3.9'
services:
  postgres-backup-prod:
    image: kartoza/pg-backup:$POSTGRES_MAJOR_VERSION
    build:
      context: .
      # Use yaml anchor for reusability
      args: &build-args-anchor
        POSTGRES_MAJOR_VERSION: ${POSTGRES_MAJOR_VERSION}
      target: postgres-backup-production

  postgres-backup-test:
    image: kartoza/pg-backup:manual-build
    build:
      context: .
      args:
        <<: *build-args-anchor
      target: postgres-backup-test